version: '3.8'

services:
  dbt:
    build:
      dockerfile: ./Dockerfile
    # for interactive shell
    stdin_open: true
    tty: true

    volumes:
      # for working directory
      - ..:/workspace:cached
      # for ssh key
      - ~/.ssh:/home/user/.ssh
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:

